version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Atieno18_
      MYSQL_DATABASE: procure
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Mount a volume for MySQL data on the host

  procure-app:
    image: nyaugenya/procurement_system:latest # This is the image of spring-boot app pulling from docker-hub repo
    container_name: procurement_management_system
    depends_on:
      - mysql
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: dev  # Reference the 'dev' profile
    volumes:
      - backend_data:/app/data  # Mount a volume for application data

volumes:
  mysql_data:  # Define the volume for MySQL data
  backend_data:  # Define the volume for application data