version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${DATA}/mongodb_data:/data/db
    networks:
      - db_net # Connect this service to the 'db_net' external network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ${DATA}/redis_data:/data/db
    networks:
      - db_net # Connect this service to the 'db_net' external network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - db_net # Connect this service to the 'db_net' external network

  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    ports:
      - "3309:3309"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DATA}/mariadb_data:/var/lib/mysql
    networks:
      - db_net # Connect this service to the 'db_net' external network

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DATA}/postgres_data:/var/lib/postgresql/data
    networks:
      - db_net # Connect this service to the 'db_net' external network

#
#  portainer:
#    image: portainer/portainer-ce:latest
#    container_name: portainer
#    command: -H unix:///var/run/docker.sock
#    ports:
#      - "9000:9000"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ${DATA}/portainer_data:/data
#    restart: always

networks:
  db_net:
    external: true # Define the 'db_net' external network

volumes:
  portainer_data:
  mongodb_data:
  mariadb_data:
  postgres_data:
  redis_data:
