spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_example
    username: rose
    password: Atieno18*?
  jpa:
    hibernate:
      ddl-auto: update

