server:
  port: 8081

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: odhiamborose466@gmail.com
    password: pbahbuxqjslsjbsd
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

logging:
  level:
    org.springframework.web: DEBUG


