apiVersion: apps/v1
kind: Deployment
metadata:
  name: procure-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: procure
  template:
    metadata:
      labels:
        app: procure
    spec:
      containers:
        - name: procure
          image: nyaugenya/procument:latest
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: rose
            - name: MYSQL_PASSWORD
              value: Atieno18_