name: Build & Deploy PMS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy PMS(Procurement Management System)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17


      - name: Build the application
        run: mvn clean install -DskipTests

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/procurement_system:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/procurement_system:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/procurement_system:latest

      - name: Delete old container
        run: |
          docker stop procurement_system || true
          docker rm procurement_system || true

      - name: Run new Docker container
        run: docker run -d -p 8085:8080 --name procurement_system ${{ secrets.DOCKER_HUB_USERNAME }}/procurement_system:latest